name: CI

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Where
        run: echo "$(pwd)"

 #     - name: Publish to AWS S3
 #       uses: opspresso/action-s3-sync@master
 #       env:
 #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 #         AWS_REGION: "us-east-1"
 #         FROM_PATH: "./target/publish"
 #         DEST_PATH: "s3://www.liskl.com/"
 #         OPTIONS: "--acl public-read"
