name: CI

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Where
        run: echo "$(pwd)"
      
      - name: What
        run: find "$(pwd)"

      - name: Deploy to S3
        if: github.ref == 'refs/heads/master'
        uses: actions/aws/cli@master
        with:
          args: s3 ls s3://www.liskl.com/index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
